scale: 1
metatile: 1
name: "Thank You Map"
bounds:
  - 1.39526
  - 47.9873
  - 3.59253
  - 49.2633
center:
  - 2.35206
  - 48.85609
  - 17
format: "png"
minzoom: 9
maxzoom: 20
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
source: 'tms://vector.mapzen.com/osm/all/{z}/{x}/{y}.mapbox'
layers:
  - earth
  - landuse
  - water
  - buildings
  - roads.geo
  - places
  - roads.label
Stylesheet:
  - "style.mss"
